import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/Header/Header";
import { roboto, sfProText } from "@/fonts";
import { StoreProvider } from "@/redux/StoreProvider";
import classNames from "classnames";
import "./globals.css";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={classNames(roboto.variable, sfProText.variable)}>
        <StoreProvider>
          <div className={styles.container}>
            <Header />
            <main className={styles.main}>{children}</main>
            <Footer />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
